name: Sprawdź nowości Cross Jeans

on:
  schedule:
    - cron: "0 7 * * *"  # 9:00 czasu polskiego (czyli 7:00 UTC)
  workflow_dispatch:

jobs:
  check-products:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run skrypt
        run: python check_crossjeans.py
